version: "3.5"

services:
    database:
        build:
            context: "./images/${VANILLA_DOCKER_DATABASE}"
        container_name: "database"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: vanilla_dev
        networks:
            - "vanilla_network"
        ports:
            - "3306:3306"
        volumes:
            - "./logs/${VANILLA_DOCKER_DATABASE}:/var/log/mysql:delegated"
            - "./resources/etc/mysql/conf.d/:/etc/mysql/conf.d/"
            - "datastorage:/var/lib/mysql"
            - code:/srv/vanilla-repositories

    php-fpm:
        depends_on:
            - "database"
        volumes:
            - code:/srv/vanilla-repositories
    nginx:
        volumes:
            - code:/srv/vanilla-repositories

volumes:
    datastorage:
        # Created by our setup script.
        external: true
    code:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: :/System/Volumes/Data/Users/stephanelafleche/Documents/vagrant-vanilla/git_repos
